### ISSUE TITLE
Test and add Windows build instructions

### ISSUE THREAD

**Issue by petros** [petros/sector-five-ii#7]
There is a section in the README file about installing the development environment on Windows. If someone could test it and add the instructions, that would be great.

Here are the recommended instructions from the book:

1. Download both Ruby and Developer Kit from https://rubyinstaller.org
2. During the Ruby installation choose to add Ruby to your PATH, and associate .rb/.rbw files with Ruby
3. Ruby should be installed somewhere like `C:\Ruby26`
4. Now run the Developer Kit installer and choose to put it in `C:\DevKit`
5. Open Command Prompt
6. `C:\> cd \DevKit`
7. `C:\DevKit> ruby dk.rb init`
8. `C:\DevKit> ruby dk.rb install`
9. `C:\DevKit> gem install gosu`
10. `C:\DevKit> gem install chipmunk`

Hopefully these instructions still work, but if not, we can probably figure out the up to date ones.

**Comment by kwacky1** [comment]
:wave: @petros 

I had a crack at this and firstly, the developer kit is bundled with the installer.

Secondly, I couldn't get chipmunk to install with the current version of Ruby (2.6.5) and I found this issue which says the chimpmunk-rb project is currently not being maintained.

https://github.com/chipmunk-rb/chipmunk/issues/25#issuecomment-478708621

So here is what worked for me:

1. Download `Ruby+Devkit 2.4.9-1 (x64)` from https://rubyinstaller.org/
2. Install and follow the prompts to add Ruby to your PATH, associate .rb.rbw files, and install the development tools
3. Open Command Prompt and run the following commands
4, `gem install gosu`
5. `gem install chipmunk`

That's it.

**Comment by petros** [comment]
Thanks so much @kwacky1! Would you like to contribute this with a PR or would you like me to do it? Either way is great! 😄.
